# Digital Ocean App Platform Specification
# Altere SEU-USUARIO para seu usuário do GitHub
name: sports-program
region: nyc
services:
  - name: api
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: andrefernandess/sports-program
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8000
    routes:
      - path: /
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
    envs:
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

